version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd"   
      MSSQL_PID: "FG86G-CHH2T-CB7NJ-XT7D2-V8V4X"
      TZ: "Asia/Bangkok"
      MSSQL_AGENT_ENABLED: "true"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    name: mssql_data
