server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api_logs
          source: api
          __path__: /var/log/sim/api.log
    pipeline_stages:
      - json:
          expressions:
            Id: Id
            Timestamp: Timestamp
            Level: Level
            Message: Message
            Request: Request
            Response: Response
            Path: Path
            Method: Method
            StatusCode: StatusCode
            RequestSizeKb: RequestSizeKb
            ResponseSizeKb: ResponseSizeKb
            Exception: Exception
      - labels:
          Level:
          Method:
      - template:
          source: StatusCode
          template: '{{ .Value }}'
      - labels:
          StatusCode:
      - timestamp:
          source: Timestamp
          format: RFC3339

  - job_name: linux_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: linux_logs
          source: linux
          __path__: /var/log/sim/linux.log
    pipeline_stages:
      - json:
          expressions:
            Timestamp: Timestamp
            Level: Level
            Message: Message
            Host: Host
            Service: Service
      - labels:
          Level:
          Host:
          Service:
      - timestamp:
          source: Timestamp
          format: RFC3339
