version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest     # Community Edition (ฟรี)
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"   # Edge endpoint ทุก service
      - "4571:4571"
    environment:
      - SERVICES=lambda,apigateway,s3,iam,sts,logs,cloudwatch
      - DEBUG=${DEBUG}
      - DATA_DIR=${DATA_DIR}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - PERSISTENCE=${PERSISTENCE}
      # อย่าใส่ LOCALSTACK_AUTH_TOKEN / LOCALSTACK_UI ใน Community
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4566/_localstack/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  # S3 Web GUI (ฟรี) — ดู/อัปโหลด/ลบไฟล์ใน S3 ของ LocalStack
  s3gui:
    image: cloudlena/s3manager:latest
    container_name: s3manager
    restart: unless-stopped
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      ENDPOINT: ${S3_ENDPOINT}
      REGION: ${S3_REGION}
      ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      USE_SSL: ${S3_USE_SSL}
      SKIP_SSL_VERIFICATION: ${S3_SKIP_SSL_VERIFICATION}
      PORT: ${S3_PORT}
      FORCE_DOWNLOAD: ${S3_FORCE_DOWNLOAD}
      ALLOW_DELETE: ${S3_ALLOW_DELETE}
      SIGNATURE_TYPE: ${S3_SIGNATURE_TYPE}
    ports:
      - "8085:8080"   # เปิด GUI ที่ http://localhost:8085

  # sqsadmin:
  #   image: pacovk/sqs-admin:latest
  #   container_name: sqs-admin
  #   restart: unless-stopped
  #   depends_on:
  #     localstack:
  #       condition: service_healthy
  #   environment:
  #     # อ่านจาก .env
  #     AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-test}
  #     AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-test}
  #     AWS_REGION: ap-southeast-1          
  #     REGION: ap-southeast-1              
  #     DEFAULT_REGION: ap-southeast-1      
  #     AWS_ENDPOINT_URL: http://localstack:4566
  #   ports:
  #     - "${SQSADMIN_HOST_PORT:-8087}:3999"   # เปิดที่ http://localhost:8087


  awsui:
    build: ./awsui
    container_name: awsui
    restart: unless-stopped
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-test}
      AWS_REGION: ap-southeast-1
      REGION: ap-southeast-1
      DEFAULT_REGION: ap-southeast-1
      AWS_ENDPOINT_URL: http://localstack:4566
    ports:
      - "8090:8000"   # เปิด GUI ที่ http://localhost:8090

  # Local Docker Registry (ตัวเลือก)
  registry:
    image: registry:2
    container_name: dev-registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: ${REGISTRY_STORAGE_PATH}
    volumes:
      - ./registry:${REGISTRY_STORAGE_PATH}

  # รัน init.sh อัตโนมัติหลัง LocalStack พร้อม
  init:
    image: localstack/localstack:latest
    container_name: init-localstack
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ./init.sh:/init.sh:ro
    entrypoint: ["/bin/sh", "-lc", "/init.sh"]
    environment:
      AWS_DEFAULT_REGION: ap-southeast-1
    restart: "no"
