version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_1
    restart: always
    ports:
      - "8540:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
